Update dlrm_data_pytorch.py
There is a typo in dlrm_data_pytorch.py when --mlperf-bin-loader flag is used.

Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1869, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1080, in run
    train_data, train_ld, test_data, test_ld = dp.make_criteo_data_and_loaders(args)
  File "/workspace/dlrm/dlrm_data_pytorch.py", line 445, in make_criteo_data_and_loaders
    value=train_data.num_samples)
AttributeError: 'CriteoBinDataset' object has no attribute 'num_samples'

Traceback (most recent call last):
  File "dlrm_s_pytorch.py", line 1869, in <module>
    run()
  File "dlrm_s_pytorch.py", line 1080, in run
    train_data, train_ld, test_data, test_ld = dp.make_criteo_data_and_loaders(args)
  File "/workspace/dlrm/dlrm_data_pytorch.py", line 467, in make_criteo_data_and_loaders
    value=test_data.num_samples)
AttributeError: 'CriteoBinDataset' object has no attribute 'num_samples'

I changed it to 'value=train_data.num_entries' and that seemed to work.